### ISSUE TITLE
Crear formato de entrega de avances de cada equipo

### ISSUE THREAD

**Issue by pacho89** [calidadudea/Admins#10]
Yo como administrador quiero crear un formato en el cual cada equipo entregará sus avances en fechas establecidas, con el fin de obtener y clasificar la información de una manera más organizada.

**Comment by breakermoob** [comment]
[Formato de trabajo por equipos.v1f.pdf](https://github.com/calidadudea/Admins/files/3720015/Formato.de.trabajo.por.equipos.v1f.pdf)
