### ISSUE TITLE
Crear formato para licitar recursos

### ISSUE THREAD

**Issue by pacho89** [calidadudea/Admins#11]
Yo como administrador quiero diseñar un formato en el cual cada equipo demandará los recursos que necesita, con el fin de solicitar estos recursos a los coordinadores y facilitarle a cada grupo.

**Comment by breakermoob** [comment]
[Formato Licitación de Recursos - Hoja 1.v1f.pdf](https://github.com/calidadudea/Admins/files/3720018/Formato.Licitacion.de.Recursos.-.Hoja.1.v1f.pdf)
