### ISSUE TITLE
Crear formato de preguntas

### ISSUE THREAD

**Issue by pacho89** [calidadudea/Admins#13]
Yo como administrador quiero diseñar un formato de preguntas con la finalidad de que cada equipo registre sus inquietudes de una manera más organizada y así evitar pérdida de información.

**Comment by breakermoob** [comment]
[Formato de Preguntas - Hoja 1.v1f.pdf](https://github.com/calidadudea/Admins/files/3720020/Formato.de.Preguntas.-.Hoja.1.v1f.pdf)
