### ISSUE TITLE
Destinar presupuesto a cada equipo

### ISSUE THREAD

**Issue by pacho89** [calidadudea/Admins#19]
Yo como administrador quiero que cada equipo trabaje bajo un presupuesto y que no se salga de este, teniendo en cuenta que existan retrasos en las entregas o necesidad de conseguir más recursos.

**Comment by breakermoob** [comment]
[Nomina Prestacion de Servicios.v1f.pdf](https://github.com/calidadudea/Admins/files/3720027/Nomina.Prestacion.de.Servicios.v1f.pdf)
