### ISSUE TITLE
Procesar peticiones de recursos

### ISSUE THREAD

**Issue by pacho89** [calidadudea/Admins#20]
o como administrador quiero recolectar las peticiones de recursos de los trabajadores para suministrarles lo necesario y mejorar el desempeño de trabajo.

**Comment by breakermoob** [comment]
[Proceso de Entrega de Peticiones - Hoja 1.v1f.pdf](https://github.com/calidadudea/Admins/files/3720028/Proceso.de.Entrega.de.Peticiones.-.Hoja.1.v1f.pdf)
