### ISSUE TITLE
Definir fechas de reuniones con cliente

### ISSUE THREAD

**Issue by pacho89** [calidadudea/Admins#7]
Yo como administrador quiero definir cada una de las fechas de las reuniones con el cliente para tener una constante retroalimentación del proyecto con el cliente.

**Comment by pacho89** [comment]
resolve #7
[Cronograma de Fechas con los clientes.docx](https://github.com/calidadudea/Admins/files/3535300/Cronograma.de.Fechas.con.los.clientes.docx)

**Comment by breakermoob** [comment]
[Informe de Reunion con los clientes VF1.pdf](https://github.com/calidadudea/Admins/files/3720013/Informe.de.Reunion.con.los.clientes.VF1.pdf)
