### ISSUE TITLE
Definir reuniones con cada equipo

### ISSUE THREAD

**Issue by pacho89** [calidadudea/Admins#8]
Yo como administrador quiero definir las fechas de las reuniones con cada equipo para tener una constante retroalimentación del proyecto y avances de cada equipo.

**Comment by breakermoob** [comment]
Documento de reuniones con los equipos. 
[Cronograma de Fechas con equipos.pdf](https://github.com/calidadudea/Admins/files/3719929/Cronograma.de.Fechas.con.equipos.pdf)
#2 #8 #9

**Comment by breakermoob** [comment]
[Cronograma de Fechas con equipos.v1f.pdf](https://github.com/calidadudea/Admins/files/3719960/Cronograma.de.Fechas.con.equipos.v1f.pdf)
#2 #8 #9

**Comment by breakermoob** [comment]
[Cronograma de Fechas con equipos.v1f.pdf](https://github.com/calidadudea/Admins/files/3719962/Cronograma.de.Fechas.con.equipos.v1f.pdf)
#2 #8 #9
